// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Pagination pagination
//
// swagger:model pagination
type Pagination struct {

	// Current page the user is on
	CurrentPage int64 `json:"currentPage,omitempty"`

	// Is there another page after?
	HasNextPage bool `json:"hasNextPage,omitempty"`

	// Is there a page before?
	HasPreviousPage bool `json:"hasPreviousPage,omitempty"`

	// Amount of elements per page
	PageSize int64 `json:"pageSize,omitempty"`

	// Sum of all existing items
	TotalItems int64 `json:"totalItems,omitempty"`

	// Sum of all pages
	TotalPages int64 `json:"totalPages,omitempty"`
}

// Validate validates this pagination
func (m *Pagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pagination based on context it is used
func (m *Pagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pagination) UnmarshalBinary(b []byte) error {
	var res Pagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
