// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpdateRatingNotesRequest update rating notes request
//
// swagger:model updateRatingNotesRequest
type UpdateRatingNotesRequest struct {

	// Ratings are from 1 - 5.
	// Example: 3
	Rating int32 `json:"rating,omitempty"`

	// user notes
	// Example: Amazing
	UserNotes string `json:"user_notes,omitempty"`
}

// Validate validates this update rating notes request
func (m *UpdateRatingNotesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this update rating notes request based on context it is used
func (m *UpdateRatingNotesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateRatingNotesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateRatingNotesRequest) UnmarshalBinary(b []byte) error {
	var res UpdateRatingNotesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
