
swagger: "2.0"
info:
  title: bookpal
  version: 0.1.0
paths:

  /api/v1/books:
    post:
      summary: Creates a book.
      operationId: createBook
      parameters:
        - name: body
          in: body
          description: book to create
          required: true
          schema:
            $ref: '../definitions/book.yml#/definitions/BookInMyDb'
      responses:
        201:
          description: Added book to database
        400:
          description: Invalid input

  /api/v1/books/search:
    get:
      summary: Searches for books using the Google Books API.
      description: Searches for books using the Google Books API. You can search by title, author or publisher.
      operationId: searchBooks
      parameters: 
        - name: query
          in: query
          description: Search term for searching books. (title, author or publisher)
          required: true
          type: string
        - name: page
          in: query
          description: Page number
          required: false
          type: integer
          default: 1
        - name: pageSize
          in: query
          description: amount of books per page
          required: false
          type: integer
          default: 10
          maximum: 30
      responses:
        200:
          description: Successful operation
          schema:
            allOf:
              - type: array
                items: 
                  $ref: '../definitions/book.yml#/definitions/Book'
              - type: object
                properties: 
                  pagination:
                    $ref: '../definitions/pagination.yml#/definitions/Pagination'
        400:
          description: Invalid status value

  /api/v1/books/{book_id}:
    get:
      summary: Gets additional details about a book.
      description: Gets additional details about a book. (title, author, publisher, description, pages, genre)
      operationId: getBookDetails
      parameters:
        - name: book_id
          in: path
          description: Id of book to return.
          required: true
          type: string
          format: uuid
      responses:
       200:
        description: Successful operation
        schema:
          $ref: '../definitions/book.yml#/definitions/Book'
       400: 
        description: Invalid ID supplied
       404:
        description: Book not found


    put:
      summary: Adds or edits a rating and eventually some notes to the book.
      description: Adds or edits a rating and eventually some notes to the book. A book can be rated 1-5 stars.
      operationId: addBookRating
      parameters:
        - name: book_id
          in: path
          description: Id of book to rate.
          required: true
          type: string
          format: uuid
        - name: newBook
          in: body
          description: Book with rating/notes.
          required: true
          schema: 
            $ref: '../definitions/book.yml#/definitions/Book'
      responses:
        200:
          description: Successful operation
          schema:
            $ref: '../definitions/book.yml#/definitions/Book'
        400:
          description: Invalid ID supplied
        404:
          description: Book not found 
