// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessTokens        string
	AppUserProfiles     string
	BookList            string
	Books               string
	Lists               string
	PasswordResetTokens string
	PushTokens          string
	RefreshTokens       string
	Users               string
}{
	AccessTokens:        "access_tokens",
	AppUserProfiles:     "app_user_profiles",
	BookList:            "book_list",
	Books:               "books",
	Lists:               "lists",
	PasswordResetTokens: "password_reset_tokens",
	PushTokens:          "push_tokens",
	RefreshTokens:       "refresh_tokens",
	Users:               "users",
}
