// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"test-project/internal/types"
)

// NewCreateListParams creates a new CreateListParams object
// no default values defined in spec.
func NewCreateListParams() CreateListParams {

	return CreateListParams{}
}

// CreateListParams contains all the bound params for the create list operation
// typically these are obtained from a http.Request
//
// swagger:parameters createList
type CreateListParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Creates a new book list with a name.
	  Required: true
	  In: body
	*/
	NewList *types.List
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreateListParams() beforehand.
func (o *CreateListParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body types.List
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("newList", "body", ""))
			} else {
				res = append(res, errors.NewParseError("newList", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.NewList = &body
			}
		}
	} else {
		res = append(res, errors.Required("newList", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CreateListParams) Validate(formats strfmt.Registry) error {
	var res []error

	// newList
	// Required: true

	// body is validated in endpoint
	//if err := o.NewList.Validate(formats); err != nil {
	//  res = append(res, err)
	//}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
