// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetAllRatedBooksParams creates a new GetAllRatedBooksParams object
// no default values defined in spec.
func NewGetAllRatedBooksParams() GetAllRatedBooksParams {

	return GetAllRatedBooksParams{}
}

// GetAllRatedBooksParams contains all the bound params for the get all rated books operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllRatedBooks
type GetAllRatedBooksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAllRatedBooksParams() beforehand.
func (o *GetAllRatedBooksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetAllRatedBooksParams) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
